apiVersion: v1
kind: Service
metadata:
  name: verdaccio
spec:
  type: NodePort
  selector:
    component: verdaccio
    stack: local
  ports:
    - protocol: TCP
      port: 4873
      nodePort: 4873
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: verdaccio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: verdaccio/verdaccio
        name: verdaccio
        ports:
        - containerPort: 4873
        resources: {}
        volumeMounts:
        - mountPath: /verdaccio/conf
          name: verdaccio-claim0
      restartPolicy: Always
      volumes:
      - name: verdaccio-claim0
        persistentVolumeClaim:
          claimName: verdaccio-claim0
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: verdaccio-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}